name: Flutter Android CI

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      USE_EPSON_DIRECT: ${{ vars.USE_EPSON_DIRECT || secrets.USE_EPSON_DIRECT || 'false' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Create Flutter project
        run: flutter create --no-overwrite .

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        env:
          USE_EPSON_DIRECT: ${{ env.USE_EPSON_DIRECT }}
        run: |
          EXTRA_ARGS=""
          if [[ "${USE_EPSON_DIRECT,,}" == "true" ]]; then
            echo "Building with Epson direct printing enabled."
            EXTRA_ARGS="--dart-define=USE_EPSON_DIRECT=true"
          else
            echo "Building without Epson direct printing."
          fi
          flutter build apk ${EXTRA_ARGS}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: lesonpos-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
